baseurl = "https://antefact.github.io/website/"
languageCode = "en-us"
title = "My New Hugo Site"
theme ="antefact"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All blog posts are defined in their own files.

  #hero
  [params.hero]
  name = "Antefact"
	claim = "Quick design iteration to _build_ interactive futures"
  replacement_verbs= ["generate","design","imagine", "build", "deploy", "fake", "discuss"]


  [[params.hero.buttons]]
    name="tell me more"
    link=""
  [[params.hero.buttons]]
    name="contacts"
    link=""

  #section about
  [params.about]
  showMoreButtonText="HOW DOES IT WORK?"

  [[params.about.weDo]]
  title="We build ante-facts, "
  description="or things before the real thing. Things you or your customer can interact with .Things that you can learn from. Things that you didn’t think about until you built them."

  [[params.about.weDo]]
  title="We iterate for you"
  description="As much as we think that post-its are great boost for innovation, many ideas come buy building and testing things."

  [[params.about.weDo]]
  title="We cut corners,"
  description="Not everything needs to be build at the same time, to understand the potential or the pitfalls of an idea we build things just real enough to be fast in iterating many of them."



  #section process
  [params.process]
  [[params.process.steps]]
  name="dive"
  title="Dive and prepare"
  paragraph="We dive in your company/studio to learn about your process and needs. We start by creating ad-hoc hands-on workshops to start working together and learn about the focus of the project."
  image=""
  align="left"

  [[params.process.steps]]
  name="iterate"
  title="Iterations(i * n)"
  paragraph="We dive in your company/studio to learn about your process and needs. We start by creating ad-hoc hands-on workshops to start working together and learn about the focus of the project."
  image=""
  align="right"


  [[params.process.steps]]
  name="document"
  title="Document and Share"
  paragraph="We document the process and create shareable learnings for you. From pictures to short videos, to prototyping kits we close the loop of the project leaving you the tools to convince others or to continue prototype and test by yourself."
  image=""
  align="left"


  #contacts

  [params.contacts]
  paragraph="Our team used to be designers and prototypers at Arduino, Frog, Tellart.We have worked for --- --- --- Now Based in glamourous CHINA to stay closer to where things are done!"

  #footer
  [params.footer]
  line1="We are in Beijing and Shanghai."
  line2="Drop us a line hi[at]antefact.com"


  # Navigation
	[params.navigation]
		brand = "brand"

	[params.navigation.links]

  [params.navigation.links.blog]
		name     = "blog"
		link = "/blog"

  [params.navigation.links.services]
  	name     = "services"
  	link = "#services"
